FROM node:20
RUN mkdir -p /usr/src/iot-auth-api
WORKDIR /usr/src/iot-auth-api
COPY package.json /usr/src/iot-auth-api
RUN npm install
COPY . /usr/src/iot-auth-api
EXPOSE 3003
CMD ["npm","start"]
