# Use official node image as the base image
FROM node:20 as build

# Set the working directory
WORKDIR /usr/local/passlink-app

# Add the source code to app
COPY ./ /usr/local/passlink-app/

# Install all the dependencies
RUN npm install

# Generate the build of the application
RUN npm run build

# Use nginx image as the base image
FROM nginx:latest

# Copy the build output to replace the default nginx contents.
COPY --from=build /usr/local/app/dist/passlink-app /usr/share/nginx/html

# Expose port 80
EXPOSE 80

